name: Reusable Workflow Release 

on:
  push:
    branches: [ main ]
  #   tags:
  #     - "fix"
  #     - "feat"
  #     - "breaking"
  #     - "docs"
  #     - "refactor"
  #     - "style"
  #     - "perf"

  repository_dispatch:
    types: [semantic-release]

  workflow_dispatch:

permissions: read-all

jobs:
  pipeline:
    permissions:
      actions: write 
      contents: write
    uses: mBlomsterberg/hanayama-workflows/.github/workflows/reusable_release.yml@main
    secrets: 
      github-token: ${{secrets.PAT}}
          